### ISSUE TITLE
Wasm and Glue JS is being encrypted

### ISSUE THREAD

**Issue by sonht0555** [joamag/boytacean#7]
@joamag I want to see how boytacean core works through wasm files and glue js files.  But it is being encrypted, how can they not be encrypted? I am trying to build another frontend for it, like kabu.io.vn I am doing for my GBA emulator.  

Please help me, I tried downloading your emukit here, it would be good if you provide it in unencrypted form.
[boytacean-wasm.zip](https://github.com/joamag/boytacean/releases/download/0.10.14/boytacean-wasm.zip)

**Comment by sonht0555** [comment]
I tried your emulator for 2 hours, it really impressed me a lot when running on IOS. Thanks for creating it

**Comment by joamag** [comment]
I'm not sure I understand what you mean by encrypted. That zip file is not encrypted and contains the WASM core (.wasm file) used for Boytacean. It uses [wasm-bindgen](https://github.com/rustwasm/wasm-bindgen) for wasm code generation, which can make it a bit trickier than usual to make use of.

You shouldn't need the [emukit](https://github.com/joamag/emukit) to run the emulator - that's just a "helper" to build the UI.

If you provide some details on what you're trying to achieve, I can probably help :).

**Comment by joamag** [comment]
@sonht0555 try to take a look here https://www.npmjs.com/package/boytacean?activeTab=code

This contains the npm package for Boytacean which is a result of running:

```bash
cargo install wasm-pack
wasm-pack build --release --target=web --out-dir=frontends/web/lib -- --features wasm
```

as state in README.md

**Comment by sonht0555** [comment]
@joamag Thank you very much, I will try to read it.

**Comment by joamag** [comment]
Closing this one as fixed
